[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan storage:link",
    "chmod -R 755 public/build",
    "cp -r public/build/* public/",
    "cp public/build/.vite/manifest.json public/build/manifest.json"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
