[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-scripts",
    "composer run-script post-autoload-dump"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
